modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/ValDesign22/WardenCraft/issues/new"

[[mods]]
modId="wardencraft"
version="0.0.7"
displayName="WardenCraft"
updateJSONURL="https://raw.githubusercontent.com/ValDesign22/WardenCraft/master/update.json"
displayURL="https://github.com/ValDesign22/WardenCraft"
logoFile="wardencraft.png"
credits="Thanks to Modding by Kaupenjoe on youtube for his tutorials"
authors="ValDesign"
description='''
WardenCraft is a Minecraft 1.19 mod that add a new armor and weapons with a custom dimension.
'''

[[dependencies.wardencraft]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.wardencraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
# [[dependencies.wardencraft]]
#     modId="geckolib"
#     mandatory=true
#     versionRange="[3.1.39,)"
#     ordering="NONE"
#     side="BOTH"